
import { Animal } from './types';

export const ANIMALS: Animal[] = [
  { id: '00', name: 'Ballena', number: '00', emoji: '🐋' },
  { id: '0', name: 'Delfín', number: '0', emoji: '🐬', imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAgkqH7-Me7I2jsHaozoTpzqofsPBszZjIWL9lqyNuWjDBsnHa8oos1CWV1taYJh98EvsrRqRBqDyj888y2c6yhtdKxcdeMaihnMo_ztsd_ZAKLkTycEVNax8YRx-0d2Emj6Knbebyacn3ISkH_NJ2qrThQycCPJ3gfmsfXeQXj30NC7i3fGrRr-GRW1DpjYdcw6LsQbXpFzcveDHVX_WjFRQyzraoXV8nYxKNY_GfFyc2kRI8sW8IIusK7H9Ig6PTROul5kTUD9GhU' },
  { id: '1', name: 'Carnero', number: '01', emoji: '🐏' },
  { id: '2', name: 'Toro', number: '02', emoji: '🐂' },
  { id: '3', name: 'Ciempiés', number: '03', emoji: '🐛' },
  { id: '4', name: 'Alacrán', number: '04', emoji: '🦂' },
  { id: '5', name: 'León', number: '05', emoji: '🦁' },
  { id: '6', name: 'Rana', number: '06', emoji: '🐸' },
  { id: '7', name: 'Perico', number: '07', emoji: '🦜' },
  { id: '8', name: 'Ratón', number: '08', emoji: '🐭' },
  { id: '9', name: 'Águila', number: '09', emoji: '🦅' },
  { id: '10', name: 'Tigre', number: '10', emoji: '🐅', imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA5QGpY7DpxKAbi5TXi-zta5-JZLGQHyF-ABkwmmX8ReWZA-Ed5LksXg1UimK-7ZC5a14XrUU7IwEtDKo6mkV1KoLCMY4wrIlf2l55fYeldPreJUUC7tgbOdSCxq7QYDRkUmLXfZ84_KVl3mP7nogzYdCxJ-dcsGokc4d5CUMhn_sq0NHePxAU-4iRLIQ9wP4icrK-6UNRorc1aWDOyYrniTgLd4coLbo_4sHlBQjqYn_WSqmmFzcxJe8qOKn4fvayiXr1gAt6_j3pj' },
  { id: '11', name: 'Gato', number: '11', emoji: '🐱' },
  { id: '12', name: 'Caballo', number: '12', emoji: '🐎' },
  { id: '13', name: 'Mono', number: '13', emoji: '🐒' },
  { id: '14', name: 'Paloma', number: '14', emoji: '🐦' },
  { id: '15', name: 'Zorro', number: '15', emoji: '🦊' },
  { id: '16', name: 'Oso', number: '16', emoji: '🐻' },
  { id: '17', name: 'Pavo', number: '17', emoji: '🦃' },
  { id: '18', name: 'Burro', number: '18', emoji: '🐴' },
  { id: '19', name: 'Chivo', number: '19', emoji: '🐐' },
  { id: '20', name: 'Cochino', number: '20', emoji: '🐷' },
  { id: '21', name: 'Gallo', number: '21', emoji: '🐓' },
  { id: '22', name: 'Camello', number: '22', emoji: '🐫' },
  { id: '23', name: 'Cebra', number: '23', emoji: '🦓' },
  { id: '24', name: 'Iguana', number: '24', emoji: '🦎' },
  { id: '25', name: 'Gallina', number: '25', emoji: '🐔' },
  { id: '26', name: 'Vaca', number: '26', emoji: '🐮' },
  { id: '27', name: 'Perro', number: '27', emoji: '🐶' },
  { id: '28', name: 'Zamuro', number: '28', emoji: '🦅' },
  { id: '29', name: 'Elefante', number: '29', emoji: '🐘' },
  { id: '30', name: 'Caimán', number: '30', emoji: '🐊' },
  { id: '31', name: 'Lapa', number: '31', emoji: '🐾' },
  { id: '32', name: 'Ardilla', number: '32', emoji: '🐿️' },
  { id: '33', name: 'Pescado', number: '33', emoji: '🐟' },
  { id: '34', name: 'Venado', number: '34', emoji: '🦌' },
  { id: '35', name: 'Jirafa', number: '35', emoji: '🦒' },
  { id: '36', name: 'Culebra', number: '36', emoji: '🐍', imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBcZLV8sCeLThGiWhxSJRK3_z8DEP_DwFrDcJAnnafgJTNC5Jp3uPPuliA_1GP60gcJ3ZokYPdrUNEN44uHlIv_Or2wSqYPxzEkrHITphrm_QGLJYXctg4gD2yJGz4qdu-FwXrYiVrBTF6vQCNiJewNckk4zZPV2W0UmGXM6vYvHP7wqd4GBGze1lCK2i9eW2HD92d1QWURQ1j2fkQErAImyR_yHPejfJUpvlgwwhKV9EI79TdKg18fXXceh-9w5DheztLTugz9WDfR' }
];
